export const GAME_CONSTANTS = {
    GRAVITY: 0.0015,
    THRUST: 0.05,
    ROTATION_THRUST: 0.08,
    INITIAL_FUEL: 100,
    SAFE_LANDING_SPEED: 5,
    SAFE_ANGLE: 10,
    TERRAIN_SEGMENTS: 20,
    LANDING_ZONE_WIDTH: 100,
    STAR_COUNT: 100,
} as const;